apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-3
  namespace: audit-zone
  labels:
    app: secure-pod
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1002
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: busybox
      image: busybox:1.35
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1002
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: tmp
          mountPath: /tmp
      resources:
        requests:
          memory: "16Mi"
          cpu: "50m"
        limits:
          memory: "32Mi"
          cpu: "100m"
  volumes:
    - name: tmp
      emptyDir: {}
  restartPolicy: Never
